config/routes.rb
Rails.application.routes.draw do
    
    devise_for :users, controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions'
    }
 
  #devise_scope :user do
  #  get 'users/sign_in', to: 'users/sessions#new'  
  #  get 'users/sign_up', to: 'users/registrations#new'
 # end
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  	root 'homes#top'

  get 'home/about' =>'homes#about'
  resources :users, only: [:show,:edit, :update,:index]do
    member do
     get 'following'
     get 'followers'
  end
  end
  resources :posts, only: [:new, :create, :index, :show, :destroy,:edit,:update] do
   resource :favorites, only: [:create, :destroy]
   resource :post_comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image

  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user


  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def show
  	@user = User.find(params[:id])
    @post = Post.new
    @posts = @user.posts
end

def edit
    @user = User.find(params[:id])
    @post = Post.new
    @posts = Post.all
if  @user ==current_user
else
    redirect_to(user_url(current_user)) unless @user == current_user
end
end

def update
     @post = Post.new
  	  @user = User.find(params[:id])
      @users = User.all
if @user.update(user_params)
    flash[:notice]="successfully"
    redirect_to user_path(@user.id)
else
    flash[:notice]="error"
    render :index
end
end

def new
    @user = User.new
end

def index
    @post = Post.new
    @posts = Post.all
     @users = User.all
     @user =current_user
     @post.user_id = current_user.id
end

def following
    @users = User.find(params[:id]).followings
end


def followers
    @users = User.find(params[:id]).followers
end
    
  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="body-wrap">
  <div id="st-container" class="st-container">
    <div class="st-pusher">
      <div class="st-content">
        <div class="st-content-inner">
          <section class="slice slice-lg sct-color-1">
            <div class="container">
              <div class="row">
                <div class="col-md-4 col-md-offset-4">
                  <div class="form-user style-1 rounded has-shadow-1">
                    <div class="form-header text-center">
                      <h2 class="form-header-title">ユーザー情報編集</h2>
                    </div>
                    <div class="form-body">
                      <%= form_for(@user) do |f| %>
  <div class="form-group">
    <label class="control-label sr-only" for="inputEmail">Name</label>
    Name<%= f.text_field :name, autofocus: true, class:"form-control", id:"inputEmail", placeholder:"名前"%>
  
     Introduction<%= f.text_field :introduction, autofocus: true, class:"form-control", id:"inputEmail", placeholder:"introduction"%>
    
  </div>
  <div class="form-group">
  <div class="user-edit-image">
   Image<%= attachment_image_tag @user, :profile_image, class: "img-circle pull-left profile-thumb", size: '60x60git'%>
  </div>
  <label class="control-label sr-only" for="inputEmail">ProfileImage</label>
  <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
  </div>


  <%= f.submit "更新する", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
  <% end %>

                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div class="conteiner">
  <div class="row">

      <div class="col-xs-offset-1 col-xs-10">
          <h2>フォロワー</h2>


          <% if @users.nil? %>
         <span>ユーザーはいません</span>

        <% else%>

           <table class="table">

              <thead>
                <tr>
                    <th>image</th>
                    <th>name</th>
                </tr>
              </thead>

              <tbody>
                <% @users.each do |user|%>
                <tr>
                    <td>
                       <%= attachment_image_tag(user, :profile_image, fallback: "temple.png", size: '100x100') %>
                    </td>
                    <td><%= user.name %></td>
                    <td>
                        <span>フォロー数：</span>
                        <%= user.followings.count %>
                    </td>
                    <td>
                        <span>フォロワー数：</span>
                        <%= user.followers.count %>
                    </td>
                    <td>
                        <%= link_to 'show', user_path(user) %>
                    </td>
                </tr>
                <% end %>
              </tbody>

           </table>

           <% end %>


    </div>

  </div>
</div>

app/views/users/following.html.erb
<div class="conteiner">
  <div class="row">

      <div class="col-xs-offset-1 col-xs-10">
          <h2>フォロー中</h2>


          <% if @users.nil? %>
         <span>ユーザーはいません</span>

        <% else%>

           <table class="table">

              <thead>
                <tr>
                    <th>image</th>
                    <th>name</th>
                </tr>
              </thead>

              <tbody>
                <% @users.each do |user|%>
                <tr>
                    <td>
                       <%= attachment_image_tag(user, :profile_image, fallback: "temple.png", size: '100x100') %>
                    </td>
                    <td><%= user.name %></td>
                    <td>
                        <span>フォロー数：</span>
                        <%= user.followings.count %>
                    </td>
                    <td>
                        <span>フォロワー数：</span>
                        <%= user.followers.count %>
                    </td>
                    <td>
                        <%= link_to 'show', user_path(user) %>
                    </td>
                </tr>
                <% end %>
              </tbody>

           </table>

           <% end %>


    </div>

  </div>
</div>

app/views/users/index.html.erb
<div class="users">
<table class="table">
  
<h1>会員一覧</h1>

	<tbody>
<tr>
  <tr>
<% @users.each do |user| %>
<tr>
<td>
<%= link_to users_path do %><%= attachment_image_tag user, :profile_image,fallback: "temple.png", class: "img-circle pull-left profile-thumb", size: '100x100' %>
<% end %></td>
<td><%=user.name %>
<%= link_to 'Show', user_path(user.id) %>
</td>
<td><% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'フォローを外す', class: 'btn btn-danger btn-block' %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.build) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'フォローする', class: 'btn btn-primary btn-block' %>

  <% end %>
<% end %></td>
<% end %>
</tr>
<% end %>
</table>
</div>

app/views/users/show.html.erb
<div class="user-show">
    <div class="row">
      <div class="col-xs-3">

<div class="mypage">
<div class="profile-container">
 <%= link_to user_path do %><%= attachment_image_tag @user, :profile_image,fallback: "temple.png", class: "img-circle pull-left profile-thumb", size: '150x150' %>
 <% end %>
</div>
<table class="table">
  <td><h3 class="profile-name">name:<%= @user.name %></h3></td>
<tr>
  <td><h3 class="introduction">introduction:<%= @user.introduction %></h3></td>
</tr>
<tr>
  <td>
    <h3 class="following">フォロー
     <%= link_to  following_user_path(@user.id) do %>
      <%= @user.followings.count %>
    <% end %>
      </h3>
  </td>
</tr>
<tr>
<td><h3 class="followers">フォロワー
  <%= link_to followers_user_path(@user.id) do %>
  <%= @user.followers.count %>
  <% end %>
  </h3></td>
</tr>
</table>
<% if @user.id == current_user.id%>
<%= link_to "", edit_user_path(@user), class: "btn col-xs-12 btn btn-default glyphicon glyphicon-cog" %>
<% end %>
</div>
</div>
<div class="col-xs-9">
  <% if @posts.present? %>
　<% @posts.each do |post| %>
  <div class="media">
	<a class="media-left" href="#">
		<%= attachment_image_tag post, :image, class: "default_image", size: '400x300' %>
	</a>
	<div class="media-body">
		<h4 class="media-heading"><%= attachment_image_tag post.user, :profile_image,fallback: "temple.png", class: "img-circle pull-left profile-thumb", size: '50x50' %>
  <%=post.user.name %></h4>
  <br>
  <br>
	Title:<%= link_to post.title, post_path(post) %>
  <br>
  <br>
  Caption:<%=post.caption %>
  <br>
  <br>
  <%= post.created_at.strftime('%Y/%m/%d') %>
  <br>
  <br>
  <%= link_to "#{post.post_comments.count} コメント", post_path(post.id) %>

  <% if post.favorited_by?(current_user) %>

  <%= link_to post_favorites_path(post), method: :delete  do %>
   <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
  <%= post.favorites.count %> いいね
  <% end %>

　<% else %>

  <%= link_to post_favorites_path(post), method: :post  do %>
    <i class="fa fa-heart-o" aria-hidden="true"></i>
    <%= post.favorites.count %> いいね
  <% end %>
  
  <% end %>
	</div>
  </div>
  <% end %>
  <% end %>

</div>
</div>
</div>