config/routes.rb
Rails.application.routes.draw do
    
    devise_for :users, controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions'
    }
 
  #devise_scope :user do
  #  get 'users/sign_in', to: 'users/sessions#new'  
  #  get 'users/sign_up', to: 'users/registrations#new'
 # end
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  	root 'homes#top'

  get 'home/about' =>'homes#about'
  resources :users, only: [:show,:edit, :update,:index]do
    member do
     get 'following'
     get 'followers'
  end
  end
  resources :posts, only: [:new, :create, :index, :show, :destroy,:edit,:update] do
   resource :favorites, only: [:create, :destroy]
   resource :post_comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
	attachment :image
	has_many :post_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy

def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
end
    
def self.search(search)
if search
    where(['caption LIKE ?', "%#{search}%"])
else
    all
end
end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
      @post = Post.new
  end

  def create
	@post = Post.new(post_params)
	@post.user_id = current_user.id
	@posts = Post.all
	@user = current_user
	@post.save
	redirect_to posts_path
  end

  def index
	@post = Post.new
	@posts = Post.all.search(params[:search])
	@user = current_user
	@post.user_id = current_user.id
	@all_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
  end

  def show
	 @newpost = Post.new
	 @post_comment = PostComment.new
  	 @post = Post.find(params[:id])
     @user = @post.user
  end

  def destroy
	@post = Post.find(params[:id])
	@post.destroy
	redirect_to posts_path
  end

  def edit
	@post = Post.find(params[:id])
  if @post.user ==current_user
  else
    redirect_to posts_path
  end
  end

  def update
	  @post = Post.find(params[:id])
      @posts = Post.all
      @user =current_user
   if @post.update(post_params)
       flash[:notice]="successfully"
    redirect_to post_path(@post.id)
   else
flash[:notice]="error"
render :edit
   end
  end

private
 def post_params
   params.require(:post).permit(:title,:caption,:image,:user_id)
 end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<h1>投稿編集</h1>
<%= form_for(@post, url: post_path) do |f| %>
<div class="row">
    <div class="col-sm-12">
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Caption</h4>
  <%= f.text_area :caption,rows:'5', class: "form-control" %>
  
  <%= f.submit '変更する',class: "btn btn-danger" %>
  
<%= link_to "詳細", post_path(@post.id) %>
<%= link_to "戻る",posts_path %>

<% end %>
</div>
</div>

app/views/posts/index.html.erb
<div class="main-contents">
　<%= form_tag(posts_path, :method => "get") do %>
  <%= text_field_tag :search %>
　<%= submit_tag "検索" ,:caption => nil ,class: "button is-info"%>
　<% end %>


　<% if @posts.present? %>
　<% @posts.each do |post| %>
  <div class="media">
	<a class="media-left" href="#">
		<%= attachment_image_tag post, :image, size: '400x300' %>
	</a>
	<div class="media-body">
		<h4 class="media-heading"><%= attachment_image_tag post.user, :profile_image,fallback: "temple.png", class: "img-circle pull-left profile-thumb", size: '50x50' %>
  <%=post.user.name %></h4>
  <br>
  <br>
	Title:<%= link_to post.title, post_path(post) %>
  <br>
  <br>
  Caption:<%=post.caption %>
  <br>
  <br>
  <%= post.created_at.strftime('%Y/%m/%d') %>
  <br>
  <br>
  <%= link_to "#{post.post_comments.count} コメント", post_path(post.id) %>

  <% if post.favorited_by?(current_user) %>

  <%= link_to post_favorites_path(post), method: :delete  do %>
   <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
  <%= post.favorites.count %> いいね
  <% end %>

　<% else %>

  <%= link_to post_favorites_path(post), method: :post  do %>
    <i class="fa fa-heart-o" aria-hidden="true"></i>
    <%= post.favorites.count %> いいね
  <% end %>
  
  <% end %>
	</div>
  </div>
  <% end %>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="new-post">
<%= form_for(@post, url: posts_path) do |f| %>
<section class="slice sct-color-1">
  <div class="post-container">
    <div class="row">
      <div class="col-md-12">

        <div class="row">
          <div class="col-md-6 col-md-offset-3 post_image_form">
            <div class="section-title-wrapper style-1 v1">
              <h3 class="section-title section-title-sm left">
                <span>新規投稿</span>
              </h3>
            </div>

            <form class="mt-20">
              <div class="row">
                <div class="col-sm-12">
                  <%= f.attachment_field :image %>
                </div>
              </div><br>
              <div class="row">
                <div class="col-sm-6">
                  <div class="form-group has-icon">
                    <h4>Title</h4>
                    <%= f.text_field :title %>
                     <h4>Caption</h4>
                    <%= f.text_area :caption,rows:'5', class: "form-control" %>
                  </div>
                </div>
                <div class="col-sm-6">
                </div>
              </div>

              <hr>

              <button type="submit" class="btn btn-lg btn-block btn-base-1 mt-20">送信</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<% end %>
</div>

app/views/posts/show.html.erb
<div class="post-show">
<h1>投稿詳細</h1>

 <div class="media">
	<a class="media-left" href="#">
	<%= attachment_image_tag @post, :image, size: '400x300' %>
	</a>
	<div class="media-body">
	<h4 class="media-heading"><%= attachment_image_tag @post.user, :profile_image,fallback: "temple.png", class: "img-circle pull-left profile-thumb", size: '50x50' %>
  <%= @post.user.name %></h4>
  <br>
  <br>
	Title:<%= @post.title %>
  <br>
  <br>
  Caption:<%= @post.caption %>
  <br>
  <br>
  <%= @post.created_at.strftime('%Y/%m/%d') %>
  <br>
  <br>
  <% if @user.id == current_user.id%>
  <%= link_to "Edit", edit_post_path(@post.id), class: "btn btn-default" %>
  <%= link_to "Destroy", post_path(@post.id), method: :delete, class: "btn btn-danger" %>
  <% end %>
  <% if @post.favorited_by?(current_user) %>
  <li>
  <%= link_to post_favorites_path(@post), method: :delete do %>
  <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
  <%= @post.favorites.count %> いいね
  <% end %>
  </li>
  <% else %>
  <li>
  <%= link_to post_favorites_path(@post), method: :book do %>
  <i class="fa fa-heart-o" aria-hidden="true"></i>
  <%= @post.favorites.count %> いいね
  <% end %>
  </li>
  <% end %>
  <br>
  <div class="comment">
  <% @post.post_comments.each do |post_comment| %>
  <li class="comment">
  <div class="comment-body bb">
  <div class="comment-avatar">
  <div class="avatar">
  </div>
  </div>
  <div class="comment-text">
  <div class="comment-author clearfix">
  <div class="comment-entry"><%= post_comment.comment %>
        
  <span class="comment-meta">
  <span class="comment-date"><%= post_comment.created_at.strftime('%Y/%m/%d') %></span>
  </span>
  <span class="link-author">by<%=post_comment.user.name %></span>
  </div>
          
  <% if post_comment.user == current_user %>
  <%= link_to "削除", post_post_comments_path(post_comment.post, post_comment), method: :delete, class: "btn btn-danger pull-right" %>
  <% end %>
  </div>
  </div>
  </div>
  </li>
  <% end %>
  </div>
  </div>
  <%= form_for [@post, @post_comment] do |f| %>
  <div class="row">
  <div class="col-sm-12">
  <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
  </div>
  </div>
  <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
  <% end %>
</div>
</div>